### ISSUE TITLE
The file SecondPriceAuction in isabelle/Auction/SingleGood has an error. 

### ISSUE THREAD

**Issue by jparsert** [formare/auctions#44]
In line 121 you are trying to prove that the SPA is well defined and in your Isar proof you try to show (∑ k ∈ N . x k) = 1 by metis and using setsum... This seems to not work anymore. Or maybe i am missing something.

**Comment by clange** [comment]
Hi, happy new year to everyone! I am no longer actively maintaining this code (@caminati, @krbr, @rowatc: Is anyone?), but I could imagine that this is a compatibility issue. At the time of implementation, this code was tested with Isabelle 2013. We submitted a _different_ subset of this GitHub project to the AFP (see https://www.isa-afp.org/entries/Vickrey_Clarke_Groves.shtml), where that code has been ported to all more recent Isabelle versions, but isabelle/Auction/SingleGood/SecondPriceAuction is not part of that code. A general approach might be to test the affected code with Isabelle 2013 (where it should work) and then with each subsequent version, while reading the release notes of these versions, and, if necessary, seeking help via the [Isabelle mailing list](https://lists.cam.ac.uk/mailman/listinfo/cl-isabelle-users).

**Comment by jparsert** [comment]
@clange Thanks a lot!
